name: networking
description: A general purpose HTTP Client for Dart, that is typed and error free.
version: 0.0.3
homepage: https://github.com/dart-pacotes/networking.dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.4
  dartz: ^0.10.1
  meta: ^1.7.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.21.1
  mocktail: ^0.3.0
